# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}
  labels:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.selectorLabels" . | nindent 4 }}
